// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MineralCollection.API.Data;

#nullable disable

namespace MineralCollection.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260425171451_UpdateMineralFields")]
    partial class UpdateMineralFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("MineralCollection.Domain.Mineral", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Begleitmineral")
                        .HasColumnType("TEXT");

                    b.Property<string>("Bemerkungen")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Breitengrad")
                        .HasColumnType("REAL");

                    b.Property<int?>("Erwerbsjahr")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Fundjahr")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Fundort")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Laengengrad")
                        .HasColumnType("REAL");

                    b.Property<string>("Land")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nummer")
                        .HasColumnType("TEXT");

                    b.Property<string>("Region")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Minerals");
                });

            modelBuilder.Entity("MineralCollection.Domain.MineralImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Caption")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .HasColumnType("TEXT");

                    b.Property<int>("MineralId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MineralId");

                    b.ToTable("MineralImages");
                });

            modelBuilder.Entity("MineralCollection.Domain.MineralImage", b =>
                {
                    b.HasOne("MineralCollection.Domain.Mineral", null)
                        .WithMany("Images")
                        .HasForeignKey("MineralId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MineralCollection.Domain.Mineral", b =>
                {
                    b.Navigation("Images");
                });
#pragma warning restore 612, 618
        }
    }
}
