// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MineralCollection.API.Data;

#nullable disable

namespace MineralCollection.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260317185057_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("MineralCollection.Domain.Mineral", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Beschreibung")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BildUrl")
                        .HasColumnType("TEXT");

                    b.Property<double>("Breitengrad")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("Funddatum")
                        .HasColumnType("TEXT");

                    b.Property<string>("Fundort")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Laengengrad")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Minerals");
                });
#pragma warning restore 612, 618
        }
    }
}
